package defpackage;

public enum d$b {
    INITIAL,
    NATIVE_START,
    WAIT_UNLOCK_STARTCLET,
    NATIVE_STARTCLET,
    RUNNING,
    ACTIVITY_PAUSE,
    TIMER_PAUSED,
    NATIVE_PAUSECLET,
    NATIVE_PAUSE,
    PAUSED,
    ACTIVITY_RESUME,
    NATIVE_RESUME,
    NATIVE_WAIT_UNLOCK_SCREEN,
    NATIVE_RESUMECLET,
    APPLICATION_EXIT,
    TIMER_FINISHED,
    NATIVE_DESTROYCLET,
    NATIVE_DESTROY,
    ACTIVITY_FINISH,
    ACTIVITY_DESTROY
}
